### PR TITLE
BYE now calls C64 warm reset vector

### PR DESCRIPTION
**Pull request by burnsauce**
Thanks @Whammo

### CODE REVIEW

**Comment by jkotlinski** [comment]
I see why this change is convenient, however it greatly limits the usefulness of `BYE`.
With the reset, it will not be possible to use `BYE` to return control to some program that did a `jsr` to Durexforth.

**Comment by burnsauce** [comment]
Hadn't considered this to be a possibility.

**Comment by Whammo** [comment]
So, to preload the stack to the reset vector, shouldn't be a problem.

**Comment by jkotlinski** [comment]
Maybe it’s doesn’t matter and BYE could even be removed?
I had a use for the current functionality once, but I am not sure I will
use Durexforth again anyway ;-)  so it doesn’t really matter too much for
me.

**Pull request closed without merging**
