### PR TITLE
 Revert to 2.0.0 RESTORE handling

### PR DESCRIPTION
**Pull request by Whammo**
This is as tight as I can make it.
It doesn't deal with RUN STOP RESTORE.

### CODE REVIEW

**Comment by jkotlinski** [comment]
Cool! And this is also compatible with RS-232?

**Comment by Whammo** [comment]
RS232 will work, any NMI not from CIA 2 and the RESTORE key calls quit.

**Comment by jkotlinski** [comment]
That is probably Fine, right?

**Comment by Whammo** [comment]
It's actually excellent! There are no complications for altering the NMI vector for hardware drivers because QUIT is always there for consistent behavior.

**Pull request merged**
