### PR TITLE
factor out `aborts` #579

### PR DESCRIPTION
**Pull request by ekipan**
Thanks for build fix.

### CODE REVIEW

**Comment by ekipan** [comment]
Apparently the issue reference doesn't totally work if it's in the title so just for completeness sake:

See #579.

**Comment by jkotlinski** [comment]
Nice, thanks for contributing! I will look at it in detail later, and see
how it fits in with other stuff.

lör 14 dec. 2024 kl. 09:44 skrev ekipan ***@***.***>:

**Comment by jkotlinski** [comment]
OK, this seems like an improvement. I am pondering various things now.

- Is the new `ABORTS` useful somewhere in DurexForth itself? I am kind of wary about adding new words. But it would feel better if there was some immediate use for it.
- Would it make sense to code golf it harder? I.e. add `(abort")` which does all the work in one word. Check condition, and either print error message and abort, or skip error message.

**Comment by ekipan** [comment]
That means every runtime-untaken `abort"` turns from a single `0branch` into rstack, counting, stack juggling etc. A bit more work. Plus I feel like you'd also need to pull a factor from `lits` to make it worth it, adding 12 cycles of `jsr rts` to every runtime string literal. Something like this?

```forth
: (lits) 1+ count 2dup + 1- ;
: lits r> (lits) >r ;

: (s") '"' parse dup c, 
here swap dup allot move ;
: s" postpone lits (s") ; immediate

\ ...

: (abort") r> (lits) >r rot 
if rvs type cr abort then 2drop ;
: abort" postpone (abort") (s") ;
immediate
```

**Comment by jkotlinski** [comment]
Uhh, that was just a bad idea of mine. It is better to use `if` .. `then` for the conditional, otherwise it gets too slow.

**Comment by jkotlinski** [comment]
How about merging the PR as is? But I would like one change, rename `aborts` to `(abort")`. Then it is clear that it is a helper word to `abort"`, and not a part of the official API.
That is, it does not need to be documented, and it can be later removed or changed without being a breaking change.

**Comment by ekipan** [comment]
This of course does add more a bit more work in the case `abort"` _is_ given a nonzero at runtime, but considering its purpose I'm sure that's okay. 12 cycles spent in the rare case a user program fails for a 9 bytes savings every time they compile the word.

**Comment by ekipan** [comment]
Or I guess only 6 cycles, since `abort` doesn't `rts` :P

**Comment by jkotlinski** [comment]
Looks good to me!
Maybe at some point this will throw an exception instead.

sön 15 dec. 2024 kl. 16:04 skrev ekipan ***@***.***>:

**Pull request merged**
