### PR TITLE
Take `#>` space from `pad`.

### PR DESCRIPTION
**Pull request by ekipan**
Per [this comment](https://github.com/jkotlinski/durexforth/discussions/548#discussioncomment-5700404).

### CODE REVIEW

**Comment by ekipan** [comment]
I guess ["no builtin words will modify this region"](https://github.com/jkotlinski/durexforth/blob/f37e8813ee8813d5c1effb02316b1e49be72a722/manual/words.adoc) is possibly no longer true. I think `see` at least uses unbounded space after `here`.

**Comment by jkotlinski** [comment]
Don't you like that `PAD` has a fixed space assigned to it? That seemed like a nice feature to me, as that space was anyway unused.

**Comment by ekipan** [comment]
I could revert `pad` at least. I don't really know my way around the memory so I worry if there's any stuff around there. It would give `see` and all of durexForth free reign after `here` again I guess.

**Comment by jkotlinski** [comment]
"I think see at least uses unbounded space after here."

Right, I remember now.. .the main reason why one would have a separate `#>` buffer, is that other words may work with the `HERE` RAM. It was very difficult to debug SEE when `.` and `dump` was overwriting the data it was supposed to debug.

**Comment by ekipan** [comment]
Okay, I'll change back `pad`.

**Comment by jkotlinski** [comment]
I wonder if `SEE` works in a way, that is incompatible with mapping the `#>` buffer to `HERE 34 +`. It almost seems like it, because as you noticed, it both writes to the `HERE` area and calls `.`?

**Comment by ekipan** [comment]
Oh. That's true. I shall have to change `see` to start writing there then. Gimme a minute.

**Comment by ekipan** [comment]
Could use a regression test with loads of branches.

**Comment by ekipan** [comment]
Can you think of any other words that write to `here` but also do number format?

**Comment by ekipan** [comment]
Alternatively!

You could give `here 34 +` to the user as `pad` and move `see`'s branch list to `$35b`. Maybe name it `there` or something for use in durexForth internal words.

Probably okay as it is, though.

**Comment by ekipan** [comment]
Did some grepping, `ls` needs fixed, I can do that. Some of `mml.fs` looks dodgy but I'm not sure. Possibly `v.fs` since it `accept`s to `here` but probably not.

**Comment by jkotlinski** [comment]
If you think about it, if all `here` accesses must change to `here 34 +`, it is no longer a net improvement. The peak RAM usage would stay the same, the only difference is that the `#>` buffer moves from one place to another.

In addition, there is the extra `34 +` code which also consumes some bytes.

**Comment by Whammo** [comment]
I think I have an ```ls``` that doesn't require buffering.

**Comment by ekipan** [comment]
You could recover most of the code bytes by defining:
```forth
( base.fs )
$35b constant there
( ... )
hide there
```
```forth
( format.fs )
: pad here 34 + ;
```
And then any durexForth words that print or need more than 34 bytes would use there instead of here, effectively swapping them as you say. It still has the benefit that user programs that misuse  `pad` or `#>` are more recoverable, but dF words have to be more careful. Maybe the benefit is not worth the cost.

**Comment by jkotlinski** [comment]
Right now, I am thinking, it would be nice if `PAD` can stay at $35b. It would be nice to use that memory for _something_. It is also nice to have a fixed-size `PAD`, that does not shrink as more words are added.

About the problem that words such as `SEE` use `HERE` as transient storage, and that it conflicts with putting `#>` at HERE + 34. How about letting `SEE` and others use `PAD` as transient storage instead? I think that might be O.K., as long as it is clearly documented.

**Comment by ekipan** [comment]
> ...many programmers are reluctant to use PAD, fearing incompatibilities with system uses. PAD is specifically intended as a programmer convenience, however, which is why we documented the fact that no standard words use it.

Sounds cut-and-dried, unless I'm missing something. However it does say that SEE may step on #>.

**Comment by jkotlinski** [comment]
As I understood it, it is OK to have a non-standard `SEE` that uses `PAD`, as long as it is documented.

**Comment by ekipan** [comment]
You likely know the standard a lot better than I do, and you definitely know durexForth better than I do. I don't know how much of dF relies on storing at HERE so my own personal opinion has changed that this PR is probably not worth it.

**Comment by jkotlinski** [comment]
How about this idea? Keep everything as in master, but move the `#>` buffer so that it grows downwards from $3fb.

$35B - $3D9 :: `pad` buffer
$3DA - $3FB :: `#>` buffer

**Comment by ekipan** [comment]
Seems like the better idea. Finally looked at the memory map, I guess it's the datasette buffer? And I would also guess the first 31 bytes are used by the interpreter or something. The [map I looked at](https://sta.c64.org/cbm64mem.html) suggests the 8 bytes before and 4 after are also unused, but I'm not confident enough to poke any more.

**Comment by ekipan** [comment]
A `#>` overrun now only steps on the end of `pad` instead of jumping to an unpredictable place in memory. A definite improvement.

**Comment by jkotlinski** [comment]
That's a nice find, [AAY64](http://unusedino.de/ec64/technical/aay/c64/zpmain.htm) also suggests there is unused space around the cassette buffer.

memmap.adoc would need an update, too.

**Pull request merged**
