### PR TITLE
Update interpreter.asm

### PR DESCRIPTION
**Pull request by Whammo**
Saving the processor state before QUIT.
  makes possible: 
 : continue $14 @ sys ;

### CODE REVIEW

**Comment by Whammo** [comment]
I think I was hasty in offering this- it doesn't account for the return stack pointer that QUIT resets. 

   I don't foresee a problem with using $310 to store sp before QUIT,  
   Perhaps I also overestimate the desirability of saving and restoring the processor state?

**Comment by jkotlinski** [comment]
What would be the typical use case for QUIT ... CONTINUE ?
Does CONTINUE exist in other Forths?

**Comment by polluks** [comment]
I found this https://www.reddit.com/r/Forth/comments/7rcxvn/continue_and_continue_in_forth/

**Comment by Whammo** [comment]
We may be in uncharted territory. I don't think Chuck Moore is available for naming. Although Elizabeth Rather chimes in frequently.

**Comment by Whammo** [comment]
QUIT doesn't actually save the processor state, a hardware interrupt saves the processor state, and then calls QUIT.
 It's more of a BREAK ...RESUME

**Comment by Whammo** [comment]
The idea here is that it takes a good deal of space to put another NMI routine in memory to save the processor state upon RUN-STOP RESTORE. 
  Saving and restoring the processor state, and saving and restoring system state allows task switching and thereby multi-tasking and possibly multi-user.

**Comment by Whammo** [comment]
Better left for a future application.

**Pull request closed without merging**
