### PR TITLE
Update io.fs

### PR DESCRIPTION
**Pull request by Whammo**
It should compile now. 
oops

### CODE REVIEW

**Comment by Whammo** [comment]
Yeah, that fixes it. Sorry for the hassle.

**Comment by Whammo** [comment]
you may have a different memory configuration so $01 needs to be changed Boolean?

**Comment by jkotlinski** [comment]
Maybe 55 should be #55 or $55

**Comment by Whammo** [comment]
I'm thinking,
```forth
 1 c@ 1 or 1 c!
 ```

**Comment by jkotlinski** [comment]
Shouldn't it be `1 c@ 3 or 1 c!`? But I think `$37 1 c!` would work just as well, and take less space.

**Comment by Whammo** [comment]
We only want to set bit 0., without disturbing the other bits.

**Comment by jkotlinski** [comment]
Are you sure? Looking here https://sta.c64.org/cbm64mem.html , it says "%x11: BASIC ROM visible at $A000-$BFFF; KERNAL ROM visible at $E000-$FFFF."
meaning both two lowest bits need to be 1?

**Comment by Whammo** [comment]
What you've added done is cool by me. I wanted to leave the >9 messages available, but it's not worth the extra code.

**Comment by Whammo** [comment]
0 or 0 = 0
0 or 1 = 1
1 or 0 = 1
1 or 1 = 1
1 c@ 1 or C! Only changes bit 0 and only if it is zero



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request closed without merging**
